package metadata

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// TestFFProbeBackend_RealMedia tests that the ffprobe backend correctly reads
// metadata tags from actual media files generated by ffmpeg
func TestFFProbeBackend_RealMedia(t *testing.T) {
	// Skip if ffmpeg is not available
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not found, skipping real media test")
	}

	tmpDir, err := os.MkdirTemp("", "probe-real-test-*")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)

	// Generate a real video file with embedded metadata using ffmpeg
	videoPath := filepath.Join(tmpDir, "test.mp4")
	cmd := exec.Command("ffmpeg",
		"-y", // Overwrite output
		"-f", "lavfi",
		"-i", "testsrc=size=1920x1080:rate=30", // Video test source
		"-f", "lavfi",
		"-i", "sine=frequency=440:duration=5", // Audio test tone (5 seconds)
		"-c:v", "libx264",
		"-preset", "ultrafast", // Fast encoding for tests
		"-t", "5", // 5 second duration
		"-metadata", "title=Test Video Title",
		"-metadata", "artist=Test Artist",
		"-metadata", "album=Test Album",
		"-metadata", "genre=Test Genre",
		"-metadata", "comment=Test Comment",
		"-metadata", "description=Test Description",
		videoPath,
	)
	cmd.Stdout = nil
	cmd.Stderr = nil
	if err := cmd.Run(); err != nil {
		t.Fatalf("ffmpeg failed to create test video: %v", err)
	}

	// Test the ffprobe backend
	backend := newFFProbeBackend()
	data, err := backend.Probe(context.Background(), videoPath)
	if err != nil {
		t.Fatalf("Probe failed: %v", err)
	}

	// Verify format
	if data.FormatName != "mov,mp4,m4a,3gp,3g2,mj2" {
		t.Errorf("Expected FormatName 'mov,mp4,m4a,3gp,3g2,mj2', got '%s'", data.FormatName)
	}

	// Duration should be ~5 seconds (allow some tolerance)
	if data.Duration < 4.5 || data.Duration > 5.5 {
		t.Errorf("Expected Duration ~5.0, got %f", data.Duration)
	}

	// Verify metadata tags
	expectedTags := map[string]string{
		"title":       "Test Video Title",
		"artist":      "Test Artist",
		"album":       "Test Album",
		"genre":       "Test Genre",
		"comment":     "Test Comment",
		"description": "Test Description",
	}

	for key, expected := range expectedTags {
		got, ok := data.Tags[key]
		if !ok {
			t.Errorf("Expected tag '%s' to exist", key)
			continue
		}
		if got != expected {
			t.Errorf("Tag '%s': expected '%s', got '%s'", key, expected, got)
		}
	}

	// Verify streams (should have video + audio)
	if len(data.Streams) != 2 {
		t.Fatalf("Expected 2 streams (video + audio), got %d", len(data.Streams))
	}

	// Find video and audio streams
	var videoStream, audioStream *StreamInfo
	for i := range data.Streams {
		if data.Streams[i].CodecType == "video" {
			videoStream = &data.Streams[i]
		}
		if data.Streams[i].CodecType == "audio" {
			audioStream = &data.Streams[i]
		}
	}

	if videoStream == nil {
		t.Fatal("Expected video stream not found")
	}
	if audioStream == nil {
		t.Fatal("Expected audio stream not found")
	}

	// Verify video stream properties
	if videoStream.CodecName != "h264" {
		t.Errorf("Expected video codec 'h264', got '%s'", videoStream.CodecName)
	}
	if videoStream.Width != 1920 {
		t.Errorf("Expected width 1920, got %d", videoStream.Width)
	}
	if videoStream.Height != 1080 {
		t.Errorf("Expected height 1080, got %d", videoStream.Height)
	}

	// Verify audio stream properties
	if audioStream.CodecName != "aac" {
		t.Errorf("Expected audio codec 'aac', got '%s'", audioStream.CodecName)
	}
	if audioStream.Channels != 1 {
		t.Errorf("Expected channels 1 (mono sine), got %d", audioStream.Channels)
	}
}

// TestFFProbeBackend_RealAudio tests metadata extraction from audio files
func TestFFProbeBackend_RealAudio(t *testing.T) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not found, skipping real audio test")
	}

	tmpDir, err := os.MkdirTemp("", "probe-audio-test-*")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)

	// Generate a real audio file with embedded metadata
	audioPath := filepath.Join(tmpDir, "test.mp3")
	cmd := exec.Command("ffmpeg",
		"-y",
		"-f", "lavfi",
		"-i", "sine=frequency=880:duration=3", // 3 second tone
		"-c:a", "libmp3lame",
		"-b:a", "128k",
		"-metadata", "title=Test Audio Track",
		"-metadata", "artist=Test Band",
		"-metadata", "album=Test Album",
		"-metadata", "genre=Rock",
		"-metadata", "track=5",
		"-metadata", "year=2024",
		audioPath,
	)
	cmd.Stdout = nil
	cmd.Stderr = nil
	if err := cmd.Run(); err != nil {
		t.Fatalf("ffmpeg failed to create test audio: %v", err)
	}

	backend := newFFProbeBackend()
	data, err := backend.Probe(context.Background(), audioPath)
	if err != nil {
		t.Fatalf("Probe failed: %v", err)
	}

	// Verify audio stream exists
	var audioStream *StreamInfo
	for i := range data.Streams {
		if data.Streams[i].CodecType == "audio" {
			audioStream = &data.Streams[i]
			break
		}
	}

	if audioStream == nil {
		t.Fatal("Expected audio stream not found")
	}

	if audioStream.CodecName != "mp3" && audioStream.CodecName != "mp3float" && audioStream.CodecName != "mp3fixed" {
		t.Errorf("Expected audio codec 'mp3*', got '%s'", audioStream.CodecName)
	}

	// Verify metadata
	if data.Tags["title"] != "Test Audio Track" {
		t.Errorf("Expected title 'Test Audio Track', got '%s'", data.Tags["title"])
	}
	if data.Tags["artist"] != "Test Band" {
		t.Errorf("Expected artist 'Test Band', got '%s'", data.Tags["artist"])
	}
	if data.Tags["album"] != "Test Album" {
		t.Errorf("Expected album 'Test Album', got '%s'", data.Tags["album"])
	}
	if data.Tags["genre"] != "Rock" {
		t.Errorf("Expected genre 'Rock', got '%s'", data.Tags["genre"])
	}
}

// TestFFProbeBackend_RealMKVWithChapters tests MKV files with chapters
func TestFFProbeBackend_RealMKVWithChapters(t *testing.T) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not found, skipping MKV chapters test")
	}

	tmpDir, err := os.MkdirTemp("", "probe-mkv-test-*")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)

	// Generate MKV with chapter metadata
	mkvPath := filepath.Join(tmpDir, "test.mkv")
	cmd := exec.Command("ffmpeg",
		"-y",
		"-f", "lavfi",
		"-i", "testsrc=size=640x480:rate=24",
		"-f", "lavfi",
		"-i", "sine=frequency=440:duration=10",
		"-c:v", "libx264",
		"-preset", "ultrafast",
		"-t", "10",
		"-metadata", "title=Chapter Test Video",
		mkvPath,
	)
	cmd.Stdout = nil
	cmd.Stderr = nil
	if err := cmd.Run(); err != nil {
		t.Fatalf("ffmpeg failed to create MKV: %v", err)
	}

	backend := newFFProbeBackend()
	data, err := backend.Probe(context.Background(), mkvPath)
	if err != nil {
		t.Fatalf("Probe failed: %v", err)
	}

	// Basic verification
	if data.FormatName != "matroska,webm" {
		t.Errorf("Expected FormatName 'matroska,webm', got '%s'", data.FormatName)
	}

	// Duration should be ~10 seconds
	if data.Duration < 9.5 || data.Duration > 10.5 {
		t.Errorf("Expected Duration ~10.0, got %f", data.Duration)
	}

	t.Logf("MKV probe: %d streams, %d chapters", len(data.Streams), len(data.Chapters))
}
